### PR TITLE
PDF bookmarks from HTML outline – clean and polish

### PR DESCRIPTION
**Pull request by stanio**
Amends #103

-   Use separate values for "none" (no) bookmark but consider children, and "exclude" tree from outline;
-   Expand a bit on documentation;
-   Add automatic HTML outline with the iText 5 library, also.

### CODE REVIEW

**Comment by pbrant** [comment]
Thanks!

**Comment by jgelo** [comment]
Is there a way to prevent the outline from being generated using a style or data attribute? 

`<html data-pdf-bookmark="none">` had no effect and I'd rather not alter the java source.

**Comment by pbrant** [comment]
@stanio Do you have any other changes you'd like to make? If not, I'll release a new version from master this weekend per @trohrberg's request.

**Comment by stanio** [comment]
@jgelo, no style support currently.  If you take a look at the javadoc for `HTMLOutline.generate()`:

> #### Example document customizations
>
> ##### Include non-heading element as bookmark (level 4)
>
>     <strong data-pdf-bookmark="4">Foo bar</strong>
>
> ##### Specify bookmark name
>
>     <tr data-pdf-bookmark="5" data-pdf-bookmark-name="Bar baz">...</tr>
>
> ##### Exclude individual heading from bookmarks
>
>     <h3 data-pdf-bookmark="none">Baz qux</h3>
>
> ##### Prevent automatic bookmarks for the whole of the document
>
>     <html data-pdf-bookmark="exclude">...</html>

**Comment by stanio** [comment]
@pbrant, I don't have additional changes currently.  I would like to see a new version including the changes so far, too.  Thank you.

**Comment by stanio** [comment]
> ... take a look at the javadoc for `HTMLOutline.generate()`...

To clarify, automatic (and customized via `data-pdf-bookmark` attributes) HTML outline doesn't take place if `<bookmark>` elements have been given in the HTML `<head>`:

```html
<html>
<head>
  ...
  <bookmarks>
    <bookmark ... />
    <bookmark ...>
      <bookmark ... />
    </bookmark>
  </bookmarks>
</head>
<body>
  ...
</body>
</html>
```

This preserves the current behavior related to usage of `<bookmark>` elements.  What has changed is documents which don't use `<bookmark>` elements now get automatic bookmarks according to the outline produced from the headings found in the document.  One may opt-out of this new behavior by specifying `data-pdf-bookmark="exclude"` on the root `<html>` element, for example.  Otherwise the result bookmarks may be customized further, as per the examples given.  One example I haven't given explicitly is:

> ##### Include the outline of nested sectioning root
>
>     <blockquote data-pdf-bookmark="none">
>       <h4>...</h4>
>       ...
>     </blockquote>

By default the outline of such nested [sectioning roots](https://www.w3.org/TR/html51/sections.html#sectioning-roots) is excluded (`data-pdf-bookmark="exclude"`) from bookmarks.  Specifying `data-pdf-bookmark="none"` on them would cause them not generating a bookmark, but considering their content/nested outline to be included in the overall document outline.

**Comment by jgelo** [comment]
@stanio, thank you for the info and examples, very much appreciated!  I'm mainly using saucer to generate reports where outline/bookmarks wouldn't make sense so I prefer to opt out entirely, however, I do have other content where outline/bookmarks would be beneficial to include.

**Comment by pbrant** [comment]
@stanio @trohrberg https://github.com/flyingsaucerproject/flyingsaucer/releases/tag/9.1.1 was released over the weekend

**Pull request merged**
