### PR TITLE
Fixes NPE introduced in 214bd386a50b2158e724d6d1b.

### PR DESCRIPTION
**Pull request by huxi**

### CODE REVIEW

**Comment by huxi** [comment]
I'm super sorry I missed this one.

**Comment by pbrant** [comment]
No worries. I'll push out 9.1.3 after work today.

**Comment by huxi** [comment]
Thanks a lot. I tested the my local SNAPSHOT the whole day but that NPE only happened while closing views... sigh...

**Comment by pbrant** [comment]
I'm afraid I didn't get to it last night, but
https://github.com/flyingsaucerproject/flyingsaucer/releases/tag/v9.1.3 is
out on Bintray now. The sync to Central should happen in a couple of hours.

**Comment by huxi** [comment]
Thanks a lot and have a nice weekend!

**Comment by huxi** [comment]
Woah! It already arrived on Maven Central!

**Pull request merged**
