### PR TITLE
Openpdf

### PR DESCRIPTION
**Pull request by asturio**
Update OpenPDF to latest Version

### CODE REVIEW

**Comment by andreasrosdal** [comment]
The most recent OpenPDF version is now 1.3.26.

**Comment by andreasrosdal** [comment]
The .travis.yml file can be changed with a GitHub Actions build file.

**Comment by andreasrosdal** [comment]
This can be updated to use OpenPDF 1.3.27

https://github.com/LibrePDF/OpenPDF/releases/tag/1.3.27

**Comment by asturio** [comment]
Updated the branch again

**Comment by dominioon** [comment]
Any plans to release the fix :)?

**Comment by pbrant** [comment]
Superseded by other PRs. Closing.

**Pull request closed without merging**
