### PR TITLE
Openpdf

### PR DESCRIPTION
**Pull request by asturio**
Please let me know if I should change anything. I renamed the -pdf module into -pdf-openpdf. The dependend modules use this "new" one.

### CODE REVIEW

**Comment by asturio** [comment]
@pbrant, @andreasrosdal: Opinions here? I don't know if renaming the directory was a good idea. What do you think?

**Comment by pbrant** [comment]
Yeah, renaming the directory would likely complicate merges.

**Comment by asturio** [comment]
Ok, I just moved the directories back to what they were. The changes are only in the POMs:

- This branch has no profile for the old itext. The openpdf profile is just no profile anymore. It's the default
- The Version for openpdf is set only in the parent-POM.

Should I changed anything else?

**Comment by pbrant** [comment]
Thanks!

**Comment by pbrant** [comment]
This is on bintray now [ https://dl.bintray.com/flyingsaucerproject/maven/org/xhtmlrenderer/flying-saucer-pdf-openpdf/9.1.9/ ] and should be on Central in a couple of hours.

**Comment by andreasrosdal** [comment]
How can we inform people? Perhaps the README?

**Comment by andreasrosdal** [comment]
I can't find flying-saucer-pdf-openpdf on Maven Central still.

**Comment by pbrant** [comment]
Hmm... the sync ran successfully, but maybe only the first one for a
particular package and version works. I've released 9.1.10 with all
artifacts and tried running sync against that version. Could you check
again later today?

**Comment by andreasrosdal** [comment]
I don't think flying-saucer-pdf-openpdf has been published to Maven Central. 

@asturio @pbrant  Can you please check this?

**Comment by asturio** [comment]
Sorry, I have no idea how to publish things on maven central. But yes, can't find flying-saucer-pdf-openpdf.

**Comment by andreasrosdal** [comment]
@asturio See https://github.com/LibrePDF/OpenPDF/wiki/Release-Process

**Comment by asturio** [comment]
@andreasrosdal Does this work for flying-saucer to?

**Comment by andreasrosdal** [comment]
I'm no expert on this, but I think you have to contact the Maven Central people first, and then you can modify and adapt the release process for flying-saucer-pdf-openpdf based on the linked article above.

**Comment by andreasrosdal** [comment]
It is important to get a release of flying-saucer-pdf-openpdf to the maven central, and tell people about it.

**Comment by pbrant** [comment]
No, I don't think that is it. We can publish anything to the
org.xhtmlrenderer groupId. It's not necessary get approval for individual
artifacts.

My guess is that there is something about the pom.xml doesn't meet
Central's requirements. It's possible that bintray's sync tool doesn't
report back all errors and releasing the staging repository silently
failed. It doesn't look like any of the artifacts for 9.1.10 made it to
Central.

I think there is a way to just have the sync tool create the staging
repository and do the release manually. I'll look into that (but it might
be the weekend before I get a chance to do it).

**Comment by pbrant** [comment]
Maybe this is it. The openpdf dependency is missing an explicit version.

      <dependency>
          <groupId>com.github.librepdf</groupId>
          <artifactId>openpdf</artifactId>
      </dependency>

**Comment by asturio** [comment]
This should be no problem for maven, as the version is defined in the parent pom. But a try won't hurt. Can you test putting a version there to see what happens?

**Comment by pbrant** [comment]
Ah, this might have been my fault then.

I published everything from master and then published just the openpdf
artifact from the openpdf branch (mvn deploy -pl flying-saucer-pdf) from
the openpdf branch. The flying-saucer-parent POM is from master. Is there
something else that I should have done?

**Comment by asturio** [comment]
Oh, this must be it... I think the change in the parent-pom from the openpdf branch can the merged in to master (if in doubt, only the dependencyManagement part). This should not mess anything in master. So the version number for OpenPDF can be forgotten in the sub-modules. When you deploy master-Version-x.y with this change, then there should be no problem deploying the same version in the openpdf branch (and only the openpdf-artifact).

One could test this localy making a mvn install for all in master, and then change branch to openpdf and do the (cd flying-saucer-pdf-openpdf; mvn install).

**Comment by pbrant** [comment]
Thanks. That worked fine locally.

I've deployed a 9.1.11 to bintray and run the sync process to Central.

**Comment by pbrant** [comment]
9.1.11 is on Central now (including the openpdf artifact).

**Comment by andreasrosdal** [comment]
Can you please update the README of this project so people can find the OpenPDF version of flying-saucer?

```
<!-- https://mvnrepository.com/artifact/org.xhtmlrenderer/flying-saucer-pdf-openpdf -->
<dependency>
    <groupId>org.xhtmlrenderer</groupId>
    <artifactId>flying-saucer-pdf-openpdf</artifactId>
    <version>9.1.11</version>
</dependency>
```


https://mvnrepository.com/artifact/org.xhtmlrenderer/flying-saucer-pdf-openpdf/9.1.11

**Pull request merged**
